application: namethatcolor
version: 1
runtime: python
api_version: 1

builtins:
- admin_redirect: on
- datastore_admin: on
- appstats: on

handlers:

- url: /load.*
  login: admin
  script: load.py

- url: .*
  script: main.py